[package]
name = "eon"
version = "0.1.0"
authors = ["Antonio Scandurra <as-cii@github.com>", "Nathan Sobo <nathan@github.com>"]

[dependencies]
lazy_static = "1.0"
smallvec = "0.6.1"
parking_lot = "0.5"
uuid = "0.6"

[dev-dependencies]
rand = "0.3"
