[package]
name = "memo"
version = "0.1.0"
authors = ["Antonio Scandurra <as-cii@github.com>", "Nathan Sobo <nathan@github.com>"]

[dependencies]
smallvec = "0.6.1"
parking_lot = "0.5"
uuid = { version = "0.6", features = ["v4"] }

[dev-dependencies]
rand = "0.3"
